/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import lombok.SneakyThrows;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @SneakyThrows
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getApp(), "app should have a greeting");
    }
}
