name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"

      - name: Check code style
        run: ./gradlew checkstyleMain
        working-directory: app

      - name: Run tests
        run: ./gradlew test
        working-directory: app

      - name: Jacoco report
        run: ./gradlew jacocoTestReport
        working-directory: app

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: app/build/reports/jacoco/test

      - name: Upload JaCoCo coverage to Qlty Cloud
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: app/build/reports/jacoco/test/jacocoTestReport.xml
