name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
      - run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
            name: jacoco-reports
            path: |
              app/build/reports/jacoco/test

      - name: Upload JaCoCo coverage to Qlty Cloud
        uses: qltysh/qlty-action/coverage@v1
        with:
            token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
            files: app/build/reports/jacoco/test/jacocoTestReport.xml